# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BRZiE9DjyZYfvxuxYYRMlB7gFvBzd0s3
"""

import pandas as pd
baza={
    "FISH": ["Umarova Mohirabonu", "Umarjonova Madinabonu", "Nomonova Ogiloy", "Astanabekova Munavvar", "Ibrohimova Shabnam", "Umaraliyeva Sadoqat", "Abdurahmonova Sadoqat", "Zokirova Mohlaroy", "Muhammadova Gulnigor", "Foziljonova Mehriniso" ],
    "Yoshi": ["19","22","19","19","19","19","19","20","19","19"],
    "Manzili": ["Oltiariq tumani", "Oltiariq tumani","Oltiariq tumani","Marg'ilon shahar", "Marg'ilon shahar","Toshloq tumani", "Oltiariq tumani", "Quva tumani", "Quva tumani","Andijon viloyati"],
    "Jinsi": ['ayol','ayol','ayol','ayol','ayol','ayol','ayol','ayol','ayol','ayol'],
    "Maktabi": ['TATUFF','FARDU','FARDU','FARDU','FARDU','ADU','ADU','ADU','ADU','TATUFF'],

}
db=pd.DataFrame(baza)
print(db)

filtr=db[db["Jinsi"]=='ayol']
print(filtr)

filtr=db[(db["Jinsi"]=='ayol') & (db ["Maktabi"]=='TATUFF') & (db ["Yoshi"]=="19")]
print(filtr)